name: couldai_user_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  uuid: ^4.3.3
  google_fonts: ^6.1.0
  supabase_flutter: ^2.5.2
  http: ^1.2.0
  shared_preferences: ^2.2.2

flutter:
  uses-material-design: true
